const apps = [
    {
        id: 1,
        name: 'Super Editor',
        category: 'Creativity',
        rating: 4.5,
        icon: 'https://placehold.co/64x64/00F076/FFFFFF/png?text=SE',
        screenshots: [
            'https://placehold.co/800x450/00F076/FFFFFF/png?text=Screenshot+1',
            'https://placehold.co/800x450/00F076/FFFFFF/png?text=Screenshot+2',
            'https://placehold.co/800x450/00F076/FFFFFF/png?text=Screenshot+3'
        ],
        description: 'Super Editor is the ultimate tool for all your creative needs. Edit photos, videos, and more with a powerful and intuitive interface.',
        link: 'https://toufikforyou.dev/app/1.apk',
        downloads: '1M+',
        ageRating: 'Everyone',
        developer: 'Creative Inc.',
        whatsNew: 'Bug fixes and performance improvements.',
        reviews: [
            { user: 'Alice', avatar: 'https://placehold.co/32x32/F53349/FFFFFF/png', rating: 5, comment: 'The best editor I have ever used!' },
            { user: 'Bob', avatar: 'https://placehold.co/32x32/00C9FF/FFFFFF/png', rating: 4, comment: 'Great app, but could use more features.' }
        ],
        featured: true
    },
    {
        id: 2,
        name: 'Office Suite',
        category: 'Productivity',
        rating: 4.8,
        icon: 'https://placehold.co/64x64/00C9FF/FFFFFF/png?text=OS',
        screenshots: [
            'https://placehold.co/800x450/00C9FF/FFFFFF/png?text=Screenshot+1',
            'https://placehold.co/800x450/00C9FF/FFFFFF/png?text=Screenshot+2'
        ],
        description: 'A complete office suite for all your productivity needs. Create documents, spreadsheets, and presentations with ease.',
        link: 'https://toufikforyou.dev/app/2.apk',
        downloads: '5M+',
        ageRating: 'Everyone',
        developer: 'Productivity Pro',
        whatsNew: 'Added new templates.',
        reviews: [],
        featured: true
    },
    {
        id: 3,
        name: 'Music Stream',
        category: 'Music',
        rating: 4.7,
        icon: 'https://placehold.co/64x64/F53349/FFFFFF/png?text=MS',
        screenshots: [
            'https://placehold.co/800x450/F53349/FFFFFF/png?text=Screenshot+1'
        ],
        description: 'Stream your favorite music from a huge library of songs. Create playlists and discover new artists.',
        link: 'https://toufikforyou.dev/app/3.apk',
        downloads: '10M+',
        ageRating: 'Teen',
        developer: 'Music Lovers',
        whatsNew: 'Improved recommendations.',
        reviews: [],
        featured: true
    },
    {
        id: 4,
        name: 'Another App',
        category: 'Social',
        rating: 4.2,
        icon: 'https://placehold.co/64x64/FFCC00/FFFFFF/png?text=AA',
        screenshots: [],
        description: 'A social app to connect with friends and family.',
        link: 'https://toufikforyou.dev/app/4.apk',
        downloads: '500K+',
        ageRating: 'Everyone',
        developer: 'Socially',
        whatsNew: 'UI improvements.',
        reviews: [],
        featured: false
    },
    {
        id: 5,
        name: 'Finance App',
        category: 'Finance',
        rating: 4.8,
        icon: 'https://placehold.co/64x64/808285/FFFFFF/png?text=FA',
        screenshots: [],
        description: 'Manage your finances with this powerful and easy-to-use app.',
        link: 'https://toufikforyou.dev/app/5.apk',
        downloads: '1M+',
        ageRating: 'Everyone',
        developer: 'Money Matters',
        whatsNew: 'Added support for more banks.',
        reviews: [],
        featured: false
    },
    {
        id: 6,
        name: 'Creative Suite',
        category: 'Creativity',
        rating: 4.6,
        icon: 'https://placehold.co/64x64/00F076/FFFFFF/png?text=CS',
        screenshots: [],
        description: 'Unleash your creativity with this amazing suite of tools.',
        link: 'https://toufikforyou.dev/app/6.apk',
        downloads: '2M+',
        ageRating: 'Everyone',
        developer: 'Creative Inc.',
        whatsNew: 'New brushes and filters.',
        reviews: [],
        featured: false
    },
    {
        id: 7,
        name: 'Gaming Hub',
        category: 'Games',
        rating: 4.7,
        icon: 'https://placehold.co/64x64/00C9FF/FFFFFF/png?text=GH',
        screenshots: [],
        description: 'The central hub for all your gaming needs.',
        link: 'https://toufikforyou.dev/app/7.apk',
        downloads: '3M+',
        ageRating: 'Teen',
        developer: 'Game On',
        whatsNew: 'New games added.',
        reviews: [],
        featured: false
    },
    {
        id: 8,
        name: 'Music Player',
        category: 'Music',
        rating: 4.4,
        icon: 'https://placehold.co/64x64/F53349/FFFFFF/png?text=MP',
        screenshots: [],
        description: 'A simple and elegant music player for your local music library.',
        link: 'https://toufikforyou.dev/app/8.apk',
        downloads: '1M+',
        ageRating: 'Everyone',
        developer: 'Music Lovers',
        whatsNew: 'Fixed a bug with playlists.',
        reviews: [],
        featured: false
    },
    {
        id: 9,
        name: 'Photo Editor',
        category: 'Photography',
        rating: 4.9,
        icon: 'https://placehold.co/64x64/FFCC00/FFFFFF/png?text=PE',
        screenshots: [],
        description: 'Edit your photos like a pro with this powerful photo editor.',
        link: 'https://toufikforyou.dev/app/9.apk',
        downloads: '5M+',
        ageRating: 'Everyone',
        developer: 'Photo Pros',
        whatsNew: 'Performance improvements.',
        reviews: [],
        featured: false
    }
];
